### ISSUE TITLE
Want to get the code for drawing AttentionMap

### ISSUE THREAD

**Issue by seTalent** [LALBJ/PAI#1]
Hello, great job. I am new to this field and want to do some related research. I don’t know how you handle the AttentionScore of each layer. I wonder if you can provide me with some ideas. Of course, it would be better if you have code. Thank you!

This is my email：
keyu925@foxmail.com

Good luck to you.

**Comment by LALBJ** [comment]
Hi, thanks for your appreciation! 

You can refer to the [attention.py](https://github.com/LALBJ/PAI/blob/master/attention.py) file. We have marked our updates to the raw LlamaAttention forward method, which is also the update method for `attention_weights` as described in our paper. 

I hope this could be helpful for you.

**Comment by seTalent** [comment]
Thank you for your reply. When I tried to add your attention to my own model (vicuna7b) and set different start_layer and end_layer, I reported the following error. Can you please find out what the problem is?
![image](https://github.com/user-attachments/assets/b399d694-8fa9-4096-9919-48bb8ee317f1)

**Comment by seTalent** [comment]
> Hi, thanks for your appreciation!
> 
> You can refer to the [attention.py](https://github.com/LALBJ/PAI/blob/master/attention.py) file. We have marked our updates to the raw LlamaAttention forward method, which is also the update method for `attention_weights` as described in our paper.
> 
> I hope this could be helpful for you.

Thanks!

**Comment by seTalent** [comment]
I tried to apply the attention to my own model (InstructBlip), Different from your code, I  feed input_embeds directly into the generate method. I wonder if this factor causes the dimension mismatch ? 
I added two line codes at the bottom to solve the problem of dimension mismatch(squeeze()), but then there were new problems...
![image](https://github.com/user-attachments/assets/0de576e6-92d0-4e25-89e3-7b20b2e111f1)

**Comment by LALBJ** [comment]
> I tried to apply the attention to my own model (InstructBlip), Different from your code, I feed input_embeds directly into the generate method. I wonder if this factor causes the dimension mismatch ? I added two line codes at the bottom to solve the problem of dimension mismatch(squeeze()), but then there were new problems... ![image](https://private-user-images.githubusercontent.com/103026143/355468579-0de576e6-92d0-4e25-89e3-7b20b2e111f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTIyOTMsIm5iZiI6MTcyMjk1MTk5MywicGF0aCI6Ii8xMDMwMjYxNDMvMzU1NDY4NTc5LTBkZTU3NmU2LTkyZDAtNGUyNS04OWUzLTdiMjBiMmUxMTFmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMzQ2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzJlZWRhMzA2YTUwODAzYmQxODVhYmVmMGRiZDhhYzYwMzU3ZTg5NTQ5N2EzNmIwZTU4NzhiMGQ5MGRlMDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z9eOWqLnXjumbtVVaU9Lq9sgVMyINZDcmSl3Xks7S4U)

The type of input (input_ids or input_embeds) for `model.generate` essentially does not affect the process for the forward function of `LlamaAttention`.

I'm sorry, but I can't determine the cause of the bug in your code based on the snippet you provided. However, we also evaluated MiniGPT-4, which, like InstructBlip, is implemented based on BLIP-2. Perhaps you could refer to the corresponding code.
