### ISSUE TITLE
PAI方法是否可以使用在flash-attention2上

### ISSUE THREAD

**Issue by yuanrr** [LALBJ/PAI#10]
我在尝试在视频理解模型上测试PAI时发现，没有办法在flash-attention2上实现该功能，似乎因为flash-attention2没有产生attention weight的中间过程，但使用原始的attention我的机器会超显存，请问作者有尝试support flash-attention2实现吗

**Comment by LALBJ** [comment]
你好，感谢对于我们工作的关注！

短时间内，暂时不会考虑支持 flash-attention2。我大致看了一下， flash-attention2 对外提供的修改接口应该不能直接支持 PAI 的改动，所以如果支持 flash-attention2 可能涉及底层的改动。

显存占用问题，建议可以从别的地方入手解决方便测试，比如减少输入的视频帧数或者缩小 kv cache 窗口大小。
