### ISSUE TITLE
关于这个工作修改的代码部分

### ISSUE THREAD

**Issue by NHeLv1** [LALBJ/PAI#12]
很棒的工作，但是Excite more precisely with an attention mode prior这一部分不是很清楚，这一部分的代码是在哪个文件实现的，它具体是怎么工作的？

**Comment by LALBJ** [comment]
你好，感谢对于我们工作的关注！

`Excite more precisely with an attention mode prior` 其实就是对应了 `start_layer` 和 `end_layer` 这两个超参数，他们会控制 `attention.py` 中扰动的注意力层。

**Comment by NHeLv1** [comment]
感谢您的回答，我仔细阅读了attention.py和CFG.py，大致理解了这个工作，很棒的想法
