### ISSUE TITLE
实验复现问题

### ISSUE THREAD

**Issue by CikZ2023** [LALBJ/PAI#5]
您好感谢您优秀的工作。我的问题是再无复现的时候我在coc0_random数据集上测试，发现即便我改了很多次alpha 数值例如0.2 0.5 0但最终的结果都一摸一样这是为什么呢。

![image](https://github.com/user-attachments/assets/765e1c35-d907-4194-b0ab-a0f946b94cfe)

**Comment by LALBJ** [comment]
您好，感谢认可！

我猜测目前的推理过程可能没有调用我们的组件。建议在 self attention 中输出 log 信息或者设置断点，确定组件是否被正确调用。

**Comment by LALBJ** [comment]
最近，也有其他同学遇到了同样的问题，最后定位到是包版本的问题，可以把包版本更新到与 PAI 一致的版本再进行测试。如果依然没有解决，可以再重新打开这个 issure。

**Comment by ZhaoChenxi-nku** [comment]
所以这个问题解决了吗，我也是和这位同学一样的问题

**Comment by yyhycx** [comment]
是的，我发现在pope所有数据集上运行都没有作用，与原始模型相比性能甚至是负优化

**Comment by xjy2020** [comment]
我也是这个问题，同学你们解决了吗？

**Comment by wenhongye** [comment]
我也是出现了这个问题，但是我显示attention确实是发生了改变
