### ISSUE TITLE
请问这项工作的核心代码在哪个文件？

### ISSUE THREAD

**Issue by FanshuoZeng** [LALBJ/PAI#6]
作者您好，这是一项非常有意义的工作。请问这项工作的核心代码在哪个文件呀？

**Comment by LALBJ** [comment]
不好意思，回复的稍微有些晚了。

两个核心功能组件的实现分别在 `attention.py` 和 `CFG.py` 文件中，你可以通过 debug 评估 chair 的代码去看一下具体的执行过程。

**Comment by FanshuoZeng** [comment]
非常感谢您的回复！
我想再请教一下，在Chair评估中，Single-turn 和 Multi-turn 的区别以及它们是由哪一个参数控制的。
谢谢。

**Comment by LALBJ** [comment]
你好，chair 本质是 image caption 任务，只包含了一个描述图像的提问，所以没有 multi-turn 多轮提问的评估。我们只在 pope 评估中加入了多轮提问的方式，具体可以参考 [pope eval](https://github.com/LALBJ/PAI?tab=readme-ov-file#pope)，分别去调用不同的评估文件即可。

**Comment by 0x4e8** [comment]
> 你好，椅子本质上是图像标题任务，只包含了一个描述图像的提问，所以没有多轮多轮提问的评估。我们只是在教皇评估中加入了多轮提问的方式，具体可以参考[教皇评估](https://github.com/LALBJ/PAI?tab=readme-ov-file#pope)，分别去调用不同的评估文件即可。

非常感谢，我明白了。

**Comment by 0x4e8** [comment]
您好，我使用Opera提供的500个样本评估Chair指标时得到的结果如下：
CHAIRs    : 27.0
CHAIRi    : 7.5
Recall    : 71.7
Len       : 99.0
我使用的CKPT为llava-1.5-7b，alpha = 0.5, gamma = 1.1。您可以提供您评估Chair的样本吗？
谢谢。

**Comment by LALBJ** [comment]
不好意思，最近在赶别的 ddl。

我们会尽快整理发布 chair 评估子集的。
