### ISSUE TITLE
generate()函数在哪个文件中实现？

### ISSUE THREAD

**Issue by FanshuoZeng** [LALBJ/PAI#7]
您好，PAI是一项非常棒的工作，在我深入学习这项工作时，我遇到了一些问题：
请问generate()函数在哪个文件中实现？
![image](https://github.com/user-attachments/assets/8ab9da70-2944-4e37-bfa0-8954f7a78b3f)

除了/transformers/generation/utils.py中的GenerationMixin类中，我没有发现其他地方实现或者继承这个函数。
谢谢！

**Comment by LALBJ** [comment]
不好意思，回复的稍微有点晚了。

generate 函数的对应实现在 transformers 库中，你可以通过检查 transformers 库的源代码去参考具体实现。
