### ISSUE TITLE
About layer prior "L"

### ISSUE THREAD

**Issue by YUECHE77** [LALBJ/PAI#8]
作者你好。

非常感谢你的杰出工作！！

在阅读论文的时候，我发现在消融实验的部分（5.4 Ablation Study），你们提到了layer prior "L"。即” the layer prior, represented as “L”, is used to determine the attention layer for intervention.“

我有一点不太理解，这个”L“你们具体是怎么得到的呢？以及，为什么说Shikra没有layer prior呢？

希望能得到回复。非常感谢！

**Comment by LALBJ** [comment]
你好，感谢认可。

在方法章节有介绍，和 attention mode prior 是同一个东西。

**Comment by YUECHE77** [comment]
看到啦，非常感谢！
