### ISSUE TITLE
有关于minigpt4相关配置

### ISSUE THREAD

**Issue by maming109** [LALBJ/PAI#9]
您好，作者，恭喜您的作品发表在eccv，我目前在复现有关代码时候，我发现llava相关内容pope任务数据集得到的效果与论文中的想过一致，但是到minigpt4感觉效果误差较大，请问对于配置minigpt的参数模型您有具体的想法与配置吗？不胜感激，美好的祝福对于您。

**Comment by maming109** [comment]
相关的模型为autodl-tmp/minigpt4/prerained_minigpt4_7b.pth  以及autodl-tmp/Vision-CAIR_vicuna-7b  我目前浮现的结果只有60左右，希望不吝赐教

**Comment by LALBJ** [comment]
你好，感谢认可！

建议先对比 baseline 方法精度是否正确。如果 baseline 精度都对不上的话，考虑是包版本或者是 checkpoint 版本的问题。
